### ISSUE TITLE
why ? 

### ISSUE THREAD

**Issue by karimamer** [torch2424/learningSVN#1]

**Comment by torch2424** [comment]
I've assigned this to you, to figure out the mystery ㊙️

**Comment by karimamer** [comment]
figured it out 🗡 🍡 🥇 🦅 🚶  🌘 🐎 🎉 🌮 🍰 🍶 ⚡️

**Comment by jaylenw** [comment]
@karimamer @torch2424 You two are hilarious!

**Comment by karimamer** [comment]
![1z5kzt](https://user-images.githubusercontent.com/2056689/32670535-e66c585c-c5f8-11e7-84e1-75e8297d21d3.jpg)

**Comment by fsilvestre90** [comment]
how about you scp those files to the server?

**Comment by karimamer** [comment]
@fsilvestre90 expanding universe

**Comment by torch2424** [comment]
But in all seriousness, I got to make this out of this learning experiment :) : https://github.com/torch2424/dotFiles/blob/master/.files_functions/functions/gvn.sh

Your mileage may vary
